[package]
name = "short_string"
version = "0.0.1"
description = "A short string implementation for Rust"
authors = ["Jacob R. Green"]
license = "Apache-2.0"
edition = "2021"

[features]
default = []

[dependencies]
static_assertions = "1.1"